### PR TITLE
Add Token 2022 Support

### PR DESCRIPTION
**Pull request by valentinmadrid**
Done:
- Create Mint
To-do:
- Transfer
- Minting
- Change to Mint State With extentions to default
- Add mint extentions

### CODE REVIEW

**Comment by buffalojoec** [comment]
Thanks for submitting this!

I think some of what you have is heading in the right direction, but ultimately I don't like the idea of having the user specify whether or not to use Token2022 at the function call level (ie. `create(&self, .., token2022: Option<bool>)`.

I think instead we should have a way for them to declare a `Mint` with a program ID - this way the `Mint` struct inherently uses Token2022 instructions instead, and the user can call the same functions they normally would. 
We can also leverage traits & generics so that only Token2022 mints get the extension instructions.

**Comment by valentinmadrid** [comment]
Using a mint with a program id would be easy and can be implemented.
One thing to take into consideration (and why I have added program id to create) is that a person could could add an unwanted program id in an instruction. For that the program should check the passed in program id, is that good devex? 
The same goes for token accounts.

**Comment by buffalojoec** [comment]
We could do it a few different ways, I have two in mind:

1. Two separate structs: `Mint` and `Mint22`.

2. Make `Mint` take some specific struct `U` ie. `Mint<U>` where `U` is a simple struct:
```rust
pub trait TokenSelector {
    fn id(&self) -> Pubkey;
}

pub struct MintLegacyProgram {}

impl TokenSelector for MintLegacyProgram {
    fn id(&self) -> Pubkey {
        spl_token::id()
    }
}

pub struct Mint2022Program {}

impl TokenSelector for Mint2022Program {
    fn id(&self) -> Pubkey {
        spl_token_2022::id()
    }
}

pub type MintLegacy<'a> = Mint<'a, MintLegacyProgram>;
pub type Mint2022<'a> = Mint<'a, Mint2022Program>;

#[derive(Clone)]
pub struct Mint<'a, T>
where
    T: TokenSelector,
{
    pub account_info: Box<AccountInfo<'a>>,
    pub token_program: Box<AccountInfo<'a>>,
    pub token_program_selection: T,
    pub data: MintState,
}
```

Then you just use the types! `MintLegacy` or `Mint2022`.

**Comment by valentinmadrid** [comment]
Sounds good. I like the thought of just using Mint and passing in a program id into the instruction to define which program should be used. This would work like token interfaces out of the box and devs could restrict to a specific token program in their code if they want to. On the other side this may not be nice for security purposes.

**Comment by buffalojoec** [comment]
They're declaring which program the mint is supposed to use in their function signature, which means they're declaring in their program config and IDL (kinda) that it's a Token2022 Mint. 

And yes, you're right. This puts us in a good spot to be able to add one additional TokenSelector for "Custom" where anyone's interface implementation can be used. But that may prove to require a little bit of additional work

**Pull request closed without merging**
